# Generated by Django 4.2.7 on 2025-09-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_year',
            field=models.IntegerField(default=2024, help_text='如：2024', verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(default='未分配班级', help_text='如：计算机科学与技术1班', max_length=50, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(default='未分配专业', max_length=100, verbose_name='专业'),
        ),
    ]
