# Generated by Django 4.2.7 on 2025-08-14 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("assistant", "助教"),
                            ("lecturer", "讲师"),
                            ("associate_professor", "副教授"),
                            ("professor", "教授"),
                            ("researcher", "研究员"),
                        ],
                        default="lecturer",
                        max_length=50,
                        verbose_name="职称",
                    ),
                ),
                (
                    "research_area",
                    models.TextField(
                        blank=True, help_text="请简要描述您的研究领域和方向", verbose_name="研究方向"
                    ),
                ),
                (
                    "office_location",
                    models.CharField(
                        blank=True,
                        help_text="如：理学院A座301室",
                        max_length=100,
                        verbose_name="办公室位置",
                    ),
                ),
                (
                    "office_hours",
                    models.TextField(
                        blank=True, help_text="请填写您的答疑时间安排", verbose_name="答疑时间"
                    ),
                ),
                (
                    "teaching_experience",
                    models.PositiveIntegerField(default=0, verbose_name="教学经验年数"),
                ),
                (
                    "education_background",
                    models.TextField(blank=True, verbose_name="教育背景"),
                ),
                (
                    "office_phone",
                    models.CharField(blank=True, max_length=15, verbose_name="办公电话"),
                ),
                ("personal_website", models.URLField(blank=True, verbose_name="个人网站")),
                (
                    "is_active_teacher",
                    models.BooleanField(default=True, verbose_name="是否在职"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师档案",
                "verbose_name_plural": "教师档案",
                "db_table": "teachers_profile",
            },
        ),
        migrations.CreateModel(
            name="TeacherNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="通知标题")),
                ("content", models.TextField(verbose_name="通知内容")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("announcement", "课程公告"),
                            ("assignment", "作业通知"),
                            ("exam", "考试通知"),
                            ("schedule_change", "课程调整"),
                            ("other", "其他"),
                        ],
                        default="announcement",
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_notices",
                        to="courses.course",
                        verbose_name="相关课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_notices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师通知",
                "verbose_name_plural": "教师通知",
                "db_table": "teachers_notice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeacherCourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("primary", "主讲教师"),
                            ("assistant", "助教"),
                            ("co_teacher", "合作教师"),
                        ],
                        default="primary",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "workload_hours",
                    models.PositiveIntegerField(default=0, verbose_name="工作量(学时)"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师课程分配",
                "verbose_name_plural": "教师课程分配",
                "db_table": "teachers_course_assignment",
                "unique_together": {("teacher", "course", "role")},
            },
        ),
    ]
