# Generated by Django 4.2.7 on 2025-08-14 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='教学楼名称')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='教学楼代码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '教学楼',
                'verbose_name_plural': '教学楼',
                'db_table': 'classrooms_building',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='教室号')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='教室名称')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='容量')),
                ('room_type', models.CharField(choices=[('lecture', '普通教室'), ('lab', '实验室'), ('computer', '机房'), ('multimedia', '多媒体教室'), ('seminar', '研讨室'), ('auditorium', '阶梯教室'), ('studio', '工作室'), ('library', '图书馆'), ('gym', '体育馆'), ('other', '其他')], default='lecture', max_length=20, verbose_name='教室类型')),
                ('floor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='楼层')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='面积(平方米)')),
                ('equipment', models.JSONField(blank=True, default=dict, help_text='存储教室设备信息，如投影仪、音响、空调等', verbose_name='设备信息')),
                ('location_description', models.TextField(blank=True, verbose_name='位置描述')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='维护备注')),
                ('last_maintenance', models.DateTimeField(blank=True, null=True, verbose_name='最后维护时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classrooms.building', verbose_name='教学楼')),
            ],
            options={
                'verbose_name': '教室',
                'verbose_name_plural': '教室',
                'db_table': 'classrooms_classroom',
                'ordering': ['building__code', 'room_number'],
                'indexes': [models.Index(fields=['building', 'room_number'], name='classrooms__buildin_692e59_idx'), models.Index(fields=['room_type'], name='classrooms__room_ty_e717c1_idx'), models.Index(fields=['capacity'], name='classrooms__capacit_032412_idx'), models.Index(fields=['is_available', 'is_active'], name='classrooms__is_avai_5e9839_idx'), models.Index(fields=['floor'], name='classrooms__floor_332e81_idx')],
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
