# Generated by Django 4.2.7 on 2025-08-14 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "teaching_quality",
                    models.PositiveIntegerField(
                        help_text="1-5分",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="教学质量",
                    ),
                ),
                (
                    "course_content",
                    models.PositiveIntegerField(
                        help_text="1-5分",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="课程内容",
                    ),
                ),
                (
                    "difficulty_level",
                    models.PositiveIntegerField(
                        help_text="1-5分",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="难度水平",
                    ),
                ),
                (
                    "workload",
                    models.PositiveIntegerField(
                        help_text="1-5分",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="课业负担",
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.PositiveIntegerField(
                        help_text="1-5分",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="总体满意度",
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="评价意见")),
                ("suggestions", models.TextField(blank=True, verbose_name="改进建议")),
                (
                    "would_recommend",
                    models.BooleanField(default=True, verbose_name="是否推荐"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评价时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enrollment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation",
                        to="courses.enrollment",
                        verbose_name="选课记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程评价",
                "verbose_name_plural": "课程评价",
                "db_table": "courses_evaluation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_type",
                    models.CharField(
                        choices=[
                            ("assignment", "作业"),
                            ("quiz", "小测验"),
                            ("midterm", "期中考试"),
                            ("final", "期末考试"),
                            ("project", "项目"),
                            ("participation", "课堂参与"),
                            ("lab", "实验"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="成绩类型",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：第一次作业、期中考试等", max_length=100, verbose_name="成绩项目名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="得分",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="满分",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="在总成绩中的权重百分比",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="权重(%)",
                    ),
                ),
                (
                    "graded_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="评分时间"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="评语")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detailed_grades",
                        to="courses.enrollment",
                        verbose_name="选课记录",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评分教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "详细成绩",
                "verbose_name_plural": "详细成绩",
                "db_table": "courses_grade",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["enrollment", "grade_type"],
                        name="courses_gra_enrollm_ca0793_idx",
                    ),
                    models.Index(
                        fields=["graded_at"], name="courses_gra_graded__4d7fa5_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="courses_gra_created_d927c1_idx"
                    ),
                ],
            },
        ),
    ]
