# Generated by Django 4.2.7 on 2025-08-14 21:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_courseevaluation_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="如：平时成绩、期中考试、期末考试等",
                        max_length=100,
                        verbose_name="成绩项目名称",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="在总成绩中的权重百分比",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="权重(%)",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="满分",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="是否为必需的成绩项目", verbose_name="是否必需"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="显示顺序，数字越小越靠前", verbose_name="排序"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_components",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "成绩组成",
                "verbose_name_plural": "成绩组成",
                "db_table": "courses_grade_component",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="grade",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的成绩组成配置",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="courses.gradecomponent",
                verbose_name="成绩组成",
            ),
        ),
        migrations.AddIndex(
            model_name="gradecomponent",
            index=models.Index(
                fields=["course", "order"], name="courses_gra_course__cc2eca_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradecomponent",
            unique_together={("course", "name")},
        ),
    ]
