# Generated by Django 4.2.7 on 2025-08-16 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="模板名称"),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("course_enrollment", "课程选课"),
                            ("grade_published", "成绩发布"),
                            ("assignment_due", "作业截止"),
                            ("schedule_change", "课程表变更"),
                            ("system_announcement", "系统公告"),
                            ("course_reminder", "课程提醒"),
                            ("exam_notification", "考试通知"),
                        ],
                        max_length=50,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(max_length=200, verbose_name="标题模板"),
                ),
                ("message_template", models.TextField(verbose_name="消息模板")),
                (
                    "email_subject_template",
                    models.CharField(blank=True, max_length=200, verbose_name="邮件主题模板"),
                ),
                (
                    "email_body_template",
                    models.TextField(blank=True, verbose_name="邮件正文模板"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text='模板变量说明，格式：{"variable_name": "description"}',
                        verbose_name="模板变量",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "通知模板",
                "verbose_name_plural": "通知模板",
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_enrollment_channels",
                    models.JSONField(default=list, verbose_name="选课通知渠道"),
                ),
                (
                    "grade_published_channels",
                    models.JSONField(default=list, verbose_name="成绩发布通知渠道"),
                ),
                (
                    "assignment_due_channels",
                    models.JSONField(default=list, verbose_name="作业截止通知渠道"),
                ),
                (
                    "schedule_change_channels",
                    models.JSONField(default=list, verbose_name="课程表变更通知渠道"),
                ),
                (
                    "system_announcement_channels",
                    models.JSONField(default=list, verbose_name="系统公告通知渠道"),
                ),
                (
                    "enable_email_notifications",
                    models.BooleanField(default=True, verbose_name="启用邮件通知"),
                ),
                (
                    "enable_websocket_notifications",
                    models.BooleanField(default=True, verbose_name="启用实时通知"),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰开始时间"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="免打扰结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知偏好",
                "verbose_name_plural": "通知偏好",
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("message", models.TextField(verbose_name="消息内容")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("course_enrollment", "课程选课"),
                            ("grade_published", "成绩发布"),
                            ("assignment_due", "作业截止"),
                            ("schedule_change", "课程表变更"),
                            ("system_announcement", "系统公告"),
                            ("course_reminder", "课程提醒"),
                            ("exam_notification", "考试通知"),
                        ],
                        default="system_announcement",
                        max_length=50,
                        verbose_name="通知类型",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对象ID"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                ("is_sent", models.BooleanField(default=False, verbose_name="是否已发送")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="发送时间"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="内容类型",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收者",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_583549_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_19df93_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_e4c995_idx"
                    ),
                ],
            },
        ),
    ]
