# Generated by Django 4.2.7 on 2025-08-16 16:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "浅色主题"), ("dark", "深色主题"), ("auto", "跟随系统")],
                        default="light",
                        max_length=10,
                        verbose_name="主题",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh-CN", "简体中文"), ("en-US", "English")],
                        default="zh-CN",
                        max_length=10,
                        verbose_name="语言",
                    ),
                ),
                (
                    "page_size",
                    models.IntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="每页显示数量",
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                        ],
                        default="YYYY-MM-DD",
                        max_length=20,
                        verbose_name="日期格式",
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("private", "私有"),
                            ("friends", "仅好友"),
                        ],
                        default="public",
                        max_length=10,
                        verbose_name="个人资料可见性",
                    ),
                ),
                ("show_email", models.BooleanField(default=True, verbose_name="显示邮箱")),
                (
                    "show_phone",
                    models.BooleanField(default=False, verbose_name="显示手机号"),
                ),
                (
                    "auto_logout",
                    models.IntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="自动登出时间（分钟）",
                    ),
                ),
                (
                    "session_timeout",
                    models.BooleanField(default=True, verbose_name="启用会话超时"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
                "db_table": "user_preferences",
            },
        ),
    ]
