# Generated by Django 4.2.7 on 2025-08-14 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('total_courses', models.PositiveIntegerField(default=0, verbose_name='授课门数')),
                ('total_hours', models.PositiveIntegerField(default=0, verbose_name='总学时')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='总学生数')),
                ('required_courses', models.PositiveIntegerField(default=0, verbose_name='必修课门数')),
                ('elective_courses', models.PositiveIntegerField(default=0, verbose_name='选修课门数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='workload_records', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师工作量',
                'verbose_name_plural': '教师工作量',
                'db_table': 'analytics_teacher_workload',
                'indexes': [models.Index(fields=['semester'], name='analytics_t_semeste_07f795_idx'), models.Index(fields=['total_hours'], name='analytics_t_total_h_cea4aa_idx')],
                'unique_together': {('teacher', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='报表名称')),
                ('report_type', models.CharField(choices=[('enrollment', '选课统计报表'), ('classroom', '教室利用率报表'), ('teacher', '教师工作量报表'), ('course', '课程统计报表'), ('schedule', '排课统计报表')], max_length=20, verbose_name='报表类型')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('data', models.JSONField(default=dict, verbose_name='报表数据')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL, verbose_name='生成人')),
            ],
            options={
                'verbose_name': '系统报表',
                'verbose_name_plural': '系统报表',
                'db_table': 'analytics_system_report',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'semester'], name='analytics_s_report__e17968_idx'), models.Index(fields=['generated_at'], name='analytics_s_generat_ff64b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('total_enrolled', models.PositiveIntegerField(default=0, verbose_name='总选课人数')),
                ('total_dropped', models.PositiveIntegerField(default=0, verbose_name='总退课人数')),
                ('current_enrolled', models.PositiveIntegerField(default=0, verbose_name='当前选课人数')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='平均分')),
                ('pass_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='及格率(%)')),
                ('excellent_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='优秀率(%)')),
                ('classroom_utilization', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='教室利用率(%)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='courses.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程统计',
                'verbose_name_plural': '课程统计',
                'db_table': 'analytics_course_statistics',
                'indexes': [models.Index(fields=['semester'], name='analytics_c_semeste_77075b_idx'), models.Index(fields=['last_updated'], name='analytics_c_last_up_29b416_idx')],
                'unique_together': {('course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomUtilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='周次')),
                ('total_time_slots', models.PositiveIntegerField(default=0, verbose_name='总时间段数')),
                ('occupied_time_slots', models.PositiveIntegerField(default=0, verbose_name='已占用时间段数')),
                ('utilization_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='利用率(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_records', to='classrooms.classroom', verbose_name='教室')),
            ],
            options={
                'verbose_name': '教室利用率',
                'verbose_name_plural': '教室利用率',
                'db_table': 'analytics_classroom_utilization',
                'indexes': [models.Index(fields=['semester', 'week_number'], name='analytics_c_semeste_acb0eb_idx'), models.Index(fields=['utilization_rate'], name='analytics_c_utiliza_6b3558_idx')],
                'unique_together': {('classroom', 'semester', 'week_number')},
            },
        ),
    ]
