# Generated by Django 4.2.7 on 2025-08-14 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='课程的唯一标识代码', max_length=20, unique=True, verbose_name='课程代码')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('english_name', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='学分')),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='学时')),
                ('course_type', models.CharField(choices=[('required', '必修课'), ('elective', '选修课'), ('public', '公共课'), ('professional', '专业课')], default='elective', max_length=20, verbose_name='课程类型')),
                ('department', models.CharField(max_length=100, verbose_name='开课院系')),
                ('semester', models.CharField(help_text='如：2024-2025-1', max_length=20, verbose_name='开课学期')),
                ('academic_year', models.CharField(help_text='如：2024-2025', max_length=10, verbose_name='学年')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('objectives', models.TextField(blank=True, verbose_name='课程目标')),
                ('max_students', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='最大选课人数')),
                ('min_students', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='最少开课人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course', verbose_name='先修课程')),
                ('teachers', models.ManyToManyField(limit_choices_to={'user_type': 'teacher'}, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses_course',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '已选课'), ('dropped', '已退课'), ('completed', '已完成'), ('failed', '未通过')], default='enrolled', max_length=20, verbose_name='状态')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='成绩')),
                ('grade', models.CharField(blank=True, help_text='如：A+, A, B+, B, C+, C, D, F', max_length=5, verbose_name='等级')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('dropped_at', models.DateTimeField(blank=True, null=True, verbose_name='退课时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='课程')),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'db_table': 'courses_enrollment',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='courses_enr_student_c86bf5_idx'), models.Index(fields=['course', 'status'], name='courses_enr_course__78d524_idx'), models.Index(fields=['enrolled_at'], name='courses_enr_enrolle_4b9ba6_idx')],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='courses_cou_departm_9688c2_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['semester'], name='courses_cou_semeste_2d692f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_type'], name='courses_cou_course__cb41c9_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'is_published'], name='courses_cou_is_acti_8e0d16_idx'),
        ),
    ]
