# Generated by Django 4.2.7 on 2025-08-14 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_year",
                    models.IntegerField(help_text="如：2024", verbose_name="入学年份"),
                ),
                ("major", models.CharField(max_length=100, verbose_name="专业")),
                (
                    "class_name",
                    models.CharField(
                        help_text="如：计算机科学与技术1班", max_length=50, verbose_name="班级"
                    ),
                ),
                (
                    "gpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4.0),
                        ],
                        verbose_name="GPA",
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="总学分",
                    ),
                ),
                (
                    "completed_credits",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="已完成学分",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("enrolled", "在读"),
                            ("suspended", "休学"),
                            ("graduated", "毕业"),
                            ("dropped", "退学"),
                        ],
                        default="enrolled",
                        max_length=20,
                        verbose_name="学籍状态",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=50, verbose_name="紧急联系人"),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, max_length=15, verbose_name="紧急联系电话"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生档案",
                "verbose_name_plural": "学生档案",
                "db_table": "students_profile",
            },
        ),
        migrations.CreateModel(
            name="StudentCourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="出勤率",
                    ),
                ),
                (
                    "assignment_completion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="作业完成率",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="courses.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生课程进度",
                "verbose_name_plural": "学生课程进度",
                "db_table": "students_course_progress",
                "unique_together": {("student", "course")},
            },
        ),
    ]
