# Generated by Django 4.2.7 on 2025-08-14 08:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：第1节课、第2节课', max_length=50, verbose_name='时间段名称')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('order', models.PositiveIntegerField(help_text='用于排序显示，数字越小越靠前', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='排序')),
                ('duration_minutes', models.PositiveIntegerField(help_text='自动计算，不需要手动填写', verbose_name='时长(分钟)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '时间段',
                'verbose_name_plural': '时间段',
                'db_table': 'schedules_timeslot',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='schedules_t_order_b52615_idx'), models.Index(fields=['start_time'], name='schedules_t_start_t_002fef_idx'), models.Index(fields=['is_active'], name='schedules_t_is_acti_4dcdac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='星期')),
                ('week_range', models.CharField(help_text='如：1-16周、1-8,10-16周', max_length=50, verbose_name='周次范围')),
                ('semester', models.CharField(help_text='如：2024-2025-1', max_length=20, verbose_name='学期')),
                ('academic_year', models.CharField(help_text='如：2024-2025', max_length=10, verbose_name='学年')),
                ('status', models.CharField(choices=[('active', '正常'), ('cancelled', '取消'), ('rescheduled', '调课'), ('suspended', '暂停')], default='active', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classrooms.classroom', verbose_name='教室')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='课程')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedules.timeslot', verbose_name='时间段')),
            ],
            options={
                'verbose_name': '课程安排',
                'verbose_name_plural': '课程安排',
                'db_table': 'schedules_schedule',
                'ordering': ['day_of_week', 'time_slot__order'],
                'indexes': [models.Index(fields=['course', 'semester'], name='schedules_s_course__ce5676_idx'), models.Index(fields=['teacher', 'semester'], name='schedules_s_teacher_a1346b_idx'), models.Index(fields=['classroom', 'day_of_week', 'time_slot'], name='schedules_s_classro_db2225_idx'), models.Index(fields=['day_of_week', 'time_slot'], name='schedules_s_day_of__cf1116_idx'), models.Index(fields=['semester', 'academic_year'], name='schedules_s_semeste_bd6895_idx'), models.Index(fields=['status'], name='schedules_s_status_60d460_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('classroom', 'day_of_week', 'time_slot', 'semester'), name='unique_classroom_schedule'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('teacher', 'day_of_week', 'time_slot', 'semester'), name='unique_teacher_schedule'),
        ),
    ]
