# Generated by Django 4.2.7 on 2025-08-16 16:13

import apps.files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.files.models.upload_to, verbose_name="文件"
                    ),
                ),
                ("file_size", models.PositiveBigIntegerField(verbose_name="文件大小(字节)")),
                ("mime_type", models.CharField(max_length=100, verbose_name="MIME类型")),
                (
                    "file_extension",
                    models.CharField(max_length=10, verbose_name="文件扩展名"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("document", "文档"),
                            ("image", "图片"),
                            ("video", "视频"),
                            ("audio", "音频"),
                            ("archive", "压缩包"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="文件分类",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="图片宽度"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="图片高度"
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, verbose_name="文件哈希"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("active", "正常"),
                            ("deleted", "已删除"),
                            ("quarantined", "隔离"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="文件状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="下载次数"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后访问时间"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="文件元数据"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="关联内容类型",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "上传文件",
                "verbose_name_plural": "上传文件",
                "db_table": "uploaded_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(max_length=32, unique=True, verbose_name="分享令牌"),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=20, verbose_name="访问密码"),
                ),
                (
                    "allow_download",
                    models.BooleanField(default=True, verbose_name="允许下载"),
                ),
                (
                    "allow_preview",
                    models.BooleanField(default=True, verbose_name="允许预览"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="过期时间"),
                ),
                (
                    "max_downloads",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最大下载次数"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(default=0, verbose_name="已下载次数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后访问时间"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="files.uploadedfile",
                        verbose_name="文件",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分享者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件分享",
                "verbose_name_plural": "文件分享",
                "db_table": "file_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=20, verbose_name="操作类型")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP地址")),
                ("user_agent", models.TextField(blank=True, verbose_name="用户代理")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="访问时间"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="files.uploadedfile",
                        verbose_name="文件",
                    ),
                ),
                (
                    "share",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="files.fileshare",
                        verbose_name="分享记录",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="访问用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "文件访问日志",
                "verbose_name_plural": "文件访问日志",
                "db_table": "file_access_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["uploaded_by", "status"], name="uploaded_fi_uploade_5b1489_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["category"], name="uploaded_fi_categor_bfb38e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["file_hash"], name="uploaded_fi_file_ha_ea7ed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["created_at"], name="uploaded_fi_created_f8998f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(
                fields=["file", "created_at"], name="file_access_file_id_d3da29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fileaccesslog",
            index=models.Index(
                fields=["user", "created_at"], name="file_access_user_id_b3c004_idx"
            ),
        ),
    ]
